version: '3.8'
services:
  db:
    image: mongo:7.0.11
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
